# Generated by Django 5.0.4 on 2024-05-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_created_at_conversation_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
