# Generated by Django 5.0.4 on 2024-04-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='keking',
        ),
    ]
